#pragma once

namespace SQL
{
	class Exception : public std::exception
	{
	private:
		int errorCode;
		std::string message;

	public:
		/**
		 * The error message is generated by sqlite3_errmsg.
		 */
		explicit Exception(int errorCode) noexcept;

		/**
		 * User-given error message.
		 */
		explicit Exception(int errorCode, std::string message) noexcept;

		/**
		 * Returns the error message.
		 */
		const char* what() const noexcept override;

		/**
		 * Returns the error code.
		 */
		int code() const noexcept;
	};
}
